language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: geyTi+ZrW0fQZTissfAqBb53bCzzVbMRHLbsOWT1gpOxRwCCgAyCevSyluC+tCdG94ik2okAYTfAIjMW+c86EeeB+VRoYp6ijyLTXwVLQpsghcKREIxEOrtvKikARyAE/xeHqykELJOU/nnkVgEmJwdB04t89/1O/w1cDnyilFU=
  app: line-football-bot
