language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: Hl+PXRcn6ye3IUjpZQWR/pGTYBDxIeQr1kJy+/D+FqDu3Ay7y/WpvRCLWaFQqNH6tEvfS/yFWhLRHeffzxENt5XPJmnOXBgYw/q9hQJ98VakN2M/MbFepGx7YacdpcjND/Wzm+q7FGGwI7lnnjkL6+FW4uQB4BLoOgxaAboO2FFpqm68a1eNfyIcRRPDcwdLIjvTGZmOBesWp+kgxN0ku35BcL3GW/FS19dWAx4cN/wj2zCz4OlvBci7Oc8Qjo+WnambYGNN3CkG/jzTdn/5x24mN65ZGPFKq5GgvjB0muHnooxXGRTZS1IT5OQU0mzj3VzwdakxNAclShP+fC616SX7JOCzLtYJyq5t9HaA5nBDmJ7ahyGpKbbHcqCU5HaSkADTUN+X1t8U1DNhyE+qnHRaUe04Nhk6HKRLU/id5S2aUfZZNox8XQyuQ0eG1kg+5+Y3oZUA6f87PkV3PwEgZKZcCihrtpyWgArujDe18p6R2jq2T0kSv/NFZFKMEwQi0aUvaTpzc5WIOQRC0/Dcc4iilbv3WKG6GlY8cRu3O/TizodGZZKLSdhBYAeI5TKCoC7fNwdCOm1VJcD4UCgOZdlFy4Y8UcRUMSDL9j/jhetAzZFvSaG1/xHRL0LqJpShTxpNOPTR/cTmG2LZAeXT699r2/exn4oMSeImn/36soA=
  app: line-football-bot
